/*

		INNER JOIN 

		SYNTAX

		SELECT COLUMN_NAME(S)
		FROM TABLE A
		INNER JOIN TABLEB ON TABLEA.COLUMN_NAME = TABLE.B.COLUMN_NAME;

*/

SELECT * FROM CUSTOMER C ;
SELECT * FROM PAYMENT;

SELECT 
	C.CUSTOMER_ID,
	C.FIRST_NAME ,
	C.LAST_NAME ,
	C.EMAIL ,
	P.AMOUNT ,
	P.PAYMENT_DATE 
FROM CUSTOMER C 
JOIN PAYMENT P 
ON C.CUSTOMER_ID = P.CUSTOMER_ID ;