/*

	PRIMARY KEY FOREIGN KEY CONSTRAINT

*/

CREATE TABLE OTOMOBILLER(
	ID 	SERIAL NOT NULL UNIQUE PRIMARY KEY,
	MARKA VARCHAR(15),
	MODEL VARCHAR(15),
	ACIKLAMA VARCHAR (500),
);

CREATE TABLE OTOMOBILLER(
	ID 	SERIAL NOT NULL UNIQUE,
	MARKA VARCHAR(15),
	MODEL VARCHAR(15),
	ACIKLAMA VARCHAR (500),
	PRIMARY KEY(ID)
);

-- NUMERIC TYPE ONDALIKLI SAYILAR IÇEREBILIR.

CREATE TABLE URUNLER(
	URUN_ID SERIAL NOT NULL UNIQUE,
	URUN_NO VARCHAR(12) NOT NULL UNIQUE, --'PL-34232' , 'TS-231313'
	AD VARCHAR(50),
	QTY NUMERIC,
	NET_PRICE NUMERIC,
	LIST_PRICE NUMERIC,
	PRIMARY KEY(URUN_ID,URUN_NO)
	);

ALTER TABLE URUNLER ADD PRIMARY KEY (URUN_ID,URUN_NO);

--EXAMPLE

CREATE TABLE VENDORS(NAME VARCHAR(250));

INSERT INTO VENDORS (NAME)
VALUES ('MICROSOFT'),
		('APPLE'),
		('SAMSUNG');
	
SELECT *FROM VENDORS;

ALTER TABLE VENDORS ADD COLUMN ID SERIAL PRIMARY KEY;

SELECT NAME,ID FROM VENDORS;

ALTER TABLE VENDORS
DROP CONSTRAINT VENDORS_PKEY


--PRIMARY KEY FOREIGN KEY

CREATE TABLE IF NOT EXISTS PRODUCTS(
	ID INT UNIQUE,
	NAME TEXT,
	PRICE NUMERIC,
	PRIMARY KEY(ID,NAME)
);

CREATE TABLE ORDERS (
	ORDER_ID INTEGER PRIMARY KEY,
	PRODUCT_ID INTEGER REFERENCES PRODUCTS(ID), 
	QUANTITY INTEGER
);

CREATE TABLE ORDER_ITEMS(
	PRODUCT_ID INT REFERENCES PRODUCTS(ID),
	ORDER_ID	INT REFERENCES ORDERS(ORDER_ID),
	QUANTITY 	INT,
	PRIMARY KEY(PRODUCT_ID, ORDER_ID)
);

INSERT INTO PRODUCTS(ID,NAME,PRICE ) VALUES (1,'SAMSUNG S4',1000);

INSERT INTO PRODUCTS(ID,NAME,PRICE ) VALUES (2,'APPLE',2000);

INSERT INTO PRODUCTS(ID,NAME,PRICE ) VALUES (3,'IPHONE',4000);


SELECT *FROM PRODUCTS

-- OLMAYAN PRODUCTS IÇIN SIPARIÞ EKLENEMEZ
INSERT INTO ORDERS(ORDER_ID ,PRODUCT_ID ,QUANTITY ) VALUES (1,4,10);


INSERT INTO ORDERS(ORDER_ID ,PRODUCT_ID ,QUANTITY ) VALUES (1,2,10);

DELETE FROM ORDERS

--SIPARIÞ VER 

INSERT INTO ORDERS(ORDER_ID ) VALUES(10);

INSERT INTO ORDER_ITEMS (ORDER_ID ,PRODUCT_ID ,QUANTITY ) VALUES (10,1,12);

SELECT * FROM ORDER_ITEMS OI 